# Category.create(name: "Dinner")
# Category.create(name: "Breakfast")
# Category.create(name: "Lunch")
Category.create(name: "Dessert")
Category.create(name: "Appetizer")
Category.create(name: "Entree")
Category.create(name: "Side")
Category.create(name: "Soup")
Category.create(name: "Salad")
Category.create(name: "Snack")

Recipe.create(name: "Chicken Salad", last_cooked_on: "02-12-2026", image: "chickensalad.webp", category_id: 1)
Recipe.create(name: "Lettuce Wraps", last_cooked_on: "02-10-2026", image: "lettucewraps.webp", category_id: 2)
